agent:
  lr: 0.0001
  gamma: 0.999
  tau: 0.002
  eps_max: 0.3
  eps_min: 0.05
  device: cuda
  kind: dd
  
train:
  transitions: 10000000
  buffer_size: 5000000
  batch_device: cpu
  batch_size: 64
  seed: 42
  saverate: ~

env:
  width: 10
  height: 10
  min_room_xy: 7
  max_room_xy: 8
  max_rooms: 1
  max_steps: 400
  timepenalty: true
  transpose: true

wandb:
  project: VacuumCleaner
  entity: breengles
  group: simple
  name: double dueling
  notes: ""
  local: False
