name: ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - jupyterlab
  - opencv
  - dlib
  - gym
  - pybullet
  - joblib
  - requests
  - tqdm
