agent:
  lr: 0.0001
  gamma: 0.999
  tau: 0.002
  eps_max: 0.5
  eps_min: 0.005
  device: cuda
  kind: ~
  
train:
  transitions: 1000000
  buffer_size: 500000
  batch_size: 64
  seed: 42
  saverate: ~

env:
  width: 20
  height: 20
  max_rooms: 3
  min_room_xy: 5
  max_room_xy: 10
  observation_size: 11
  vision_radius: 5
  max_steps: 400
  timepenalty: 1
  transpose: true

wandb:
  project: VacuumCleaner
  entity: breengles
  group: task
  name: dqn
  notes: ""
  local: False
