

env:
  width: 30
  height: 30
  min_room_xy: 7
  max_room_xy: 14
  max_steps: 400
  timepenalty: true

wandb:
  project: "VacuumCleaner"
  entity: "breengles"
  group: "baseline_conv"
  name: "eps_min=0.3 | timepenalty"
  notes: ""
  local: False
