train:
  epochs: 500
  seed: 42
  saverate: ~

env:
  width: 10
  height: 10
  min_room_xy: 7
  max_room_xy: 8
  max_rooms: 1
  max_steps: 400

wandb:
  project: VacuumCleaner
  entity: breengles
  group: ppo
  name: simple
  notes: ""
  local: False
