train:
  epochs: 500
  seed: 42
  saverate: ~

env:
  width: 20
  height: 20
  max_rooms: 3
  min_room_xy: 5
  max_room_xy: 10
  observation_size: 11
  vision_radius: 5
  max_steps: 2000
  timepenalty: 1
  reward_for_new: 1

wandb:
  project: VacuumCleaner
  entity: breengles
  group: task
  name: ppo | tp +new
  notes: ""
  local: False
