agent:
  lr: 0.0001
  gamma: 0.999
  tau: 0.002
  eps_max: 1
  eps_min: 0.3
  device: cuda
  kind: double
  
train:
  transitions: 1000000
  buffer_size: 500000
  batch_size: 64
  seed: 42
  saverate: ~

env:
  width: 30
  height: 30
  min_room_xy: 7
  max_room_xy: 14
  max_steps: 400
  timepenalty: true

wandb:
  project: VacuumCleaner
  entity: breengles
  group: baseline_conv
  name: double
  notes: ""
  local: False
