train:
  transitions: 10000000
  hidden_dim: 128
  buffer_size: 1000000
  batch_size: 256
  actor_lr: 0.0001
  gamma: 0.999
  tau: 0.002
  sigma_max: 2
  sigma_min: 0
  seed: 42
  saverate: ~
  device: "cpu"

env_config:
  width: 30
  height: 30
  min_room_xy: 7
  max_room_xy: 14
  max_steps: 400

wandb:
  project: "VacuumCleaner"
  entity: "breengles"
  group: "test"
  name: "64"
  notes: ""
  local: False
